server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver 169.254.169.253 valid=30s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(health|predict|jobs|model) {
        set $upstream http://api:8000;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
